import Foundation
import SwiftUI

// MARK: - International Localization System

public enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "English (US)"
    case spanish = "Español"
    case french = "Français"
    case german = "Deutsch"
    case japanese = "日本語"
    case chinese = "简体中文"
    case italian = "Italiano"
    case korean = "한국어"
    case portuguese = "Português"
    case arabic = "العربية"

    public var id: String { rawValue }

    public var code: String {
        switch self {
        case .english: return "EN"
        case .spanish: return "ES"
        case .french: return "FR"
        case .german: return "DE"
        case .japanese: return "JA"
        case .chinese: return "ZH"
        case .italian: return "IT"
        case .korean: return "KO"
        case .portuguese: return "PT"
        case .arabic: return "AR"
        }
    }

    public var flag: String {
        switch self {
        case .english: return "🇺🇸"
        case .spanish: return "🇪🇸"
        case .french: return "🇫🇷"
        case .german: return "🇩🇪"
        case .japanese: return "🇯🇵"
        case .chinese: return "🇨🇳"
        case .italian: return "🇮🇹"
        case .korean: return "🇰🇷"
        case .portuguese: return "🇧🇷"
        case .arabic: return "🇸🇦"
        }
    }

    public var greeting: String {
        switch self {
        case .english: return "Hello"
        case .spanish: return "Hola"
        case .french: return "Bonjour"
        case .german: return "Hallo"
        case .japanese: return "こんにちは"
        case .chinese: return "你好"
        case .italian: return "Ciao"
        case .korean: return "안녕하세요"
        case .portuguese: return "Olá"
        case .arabic: return "مرحبا"
        }
    }
}

public struct LocalizedStrings {
    // MARK: - Navigation Tabs & Menus
    public static func tabTitle(_ tab: String, lang: String) -> String {
        switch lang {
        case "Español":
            switch tab {
            case "Battery": return "Batería"
            case "Apps": return "Aplicaciones"
            case "Desktop": return "Escritorio"
            case "Themes": return "Temas"
            case "Formations": return "Formaciones"
            case "Mouse & Trails": return "Cursor y Estelas"
            case "Entities & Pets": return "Mascotas y Compañeros"
            case "Sounds": return "Efectos de Sonido"
            case "Wallpaper": return "Fondo de Pantalla"
            case "Motion & FX": return "Movimiento y Efectos"
            case "Status Bar": return "Barra de menús"
            case "VIP Packs": return "Paquetes VIP"
            case "General": return "Ajustes Generales"
            default: return tab
            }
        case "Français":
            switch tab {
            case "Battery": return "Batterie"
            case "Apps": return "Applications"
            case "Desktop": return "Bureau"
            case "Themes": return "Thèmes"
            case "Formations": return "Formations"
            case "Mouse & Trails": return "Curseur & Traînées"
            case "Entities & Pets": return "Compagnons & Créatures"
            case "Sounds": return "Effets Sonores"
            case "Wallpaper": return "Fond d'écran"
            case "Motion & FX": return "Mouvements & Effets"
            case "Status Bar": return "Barre des menus"
            case "VIP Packs": return "Packs VIP"
            case "General": return "Général"
            default: return tab
            }
        case "Deutsch":
            switch tab {
            case "Battery": return "Batterie"
            case "Apps": return "Apps"
            case "Desktop": return "Schreibtisch"
            case "Themes": return "Designs"
            case "Formations": return "Formationen"
            case "Mouse & Trails": return "Zeiger & Spuren"
            case "Entities & Pets": return "Begleiter & Wesen"
            case "Sounds": return "Soundeffekte"
            case "Wallpaper": return "Hintergrundbild"
            case "Motion & FX": return "Bewegung & Effekte"
            case "Status Bar": return "Menüleiste"
            case "VIP Packs": return "VIP-Erweiterungen"
            case "General": return "Allgemein"
            default: return tab
            }
        case "日本語":
            switch tab {
            case "Battery": return "バッテリー"
            case "Apps": return "アプリ"
            case "Desktop": return "デスクトップ"
            case "Themes": return "テーマ"
            case "Formations": return "フォーメーション"
            case "Mouse & Trails": return "カーソルと軌跡"
            case "Entities & Pets": return "デスクトップペット"
            case "Sounds": return "サウンド効果"
            case "Wallpaper": return "壁紙"
            case "Motion & FX": return "モーション＆エフェクト"
            case "Status Bar": return "メニューバー"
            case "VIP Packs": return "VIP 拡張パック"
            case "General": return "一般設定"
            default: return tab
            }
        case "简体中文":
            switch tab {
            case "Battery": return "电池与状态"
            case "Apps": return "应用程序"
            case "Desktop": return "桌面布局"
            case "Themes": return "主题风格"
            case "Formations": return "阵列布局"
            case "Mouse & Trails": return "光标与轨迹"
            case "Entities & Pets": return "灵动桌面宠物"
            case "Sounds": return "音效反馈"
            case "Wallpaper": return "壁纸与背景"
            case "Motion & FX": return "动态视觉特效"
            case "Status Bar": return "菜单栏"
            case "VIP Packs": return "VIP 尊享扩展"
            case "General": return "通用设置"
            default: return tab
            }
        case "Italiano":
            switch tab {
            case "Apps": return "Applicazioni"
            case "Desktop": return "Scrivania"
            case "Themes": return "Temi"
            case "Formations": return "Formazioni"
            case "Mouse & Trails": return "Puntatore e Tracce"
            case "Entities & Pets": return "Compagni e Creature"
            case "Sounds": return "Effetti Sonori"
            case "Wallpaper": return "Sfondo Scrivania"
            case "Motion & FX": return "Movimento ed Effetti"
            case "Status Bar": return "Barra dei menu"
            case "VIP Packs": return "Pacchetti VIP"
            case "General": return "Generale"
            default: return tab
            }
        case "한국어":
            switch tab {
            case "Apps": return "앱"
            case "Desktop": return "데스크탑"
            case "Themes": return "테마"
            case "Formations": return "포메이션"
            case "Mouse & Trails": return "커서 및 궤적"
            case "Entities & Pets": return "인터랙티브 펫"
            case "Sounds": return "사운드 효과"
            case "Wallpaper": return "배경화면"
            case "Motion & FX": return "모션 및 시각 효과"
            case "Status Bar": return "메뉴 막대"
            case "VIP Packs": return "VIP 확장팩"
            case "General": return "일반 설정"
            default: return tab
            }
        case "Português":
            switch tab {
            case "Apps": return "Aplicativos"
            case "Desktop": return "Área de Trabalho"
            case "Themes": return "Temas"
            case "Formations": return "Formações"
            case "Mouse & Trails": return "Cursor e Rastros"
            case "Entities & Pets": return "Pets e Companheiros"
            case "Sounds": return "Efeitos Sonoros"
            case "Wallpaper": return "Papel de Parede"
            case "Motion & FX": return "Movimento e Efeitos"
            case "Status Bar": return "Barra de Menus"
            case "VIP Packs": return "Pacotes VIP"
            case "General": return "Geral"
            default: return tab
            }
        case "العربية":
            switch tab {
            case "Apps": return "التطبيقات"
            case "Desktop": return "سطح المكتب"
            case "Themes": return "السمات"
            case "Formations": return "التشكيلات المكانية"
            case "Mouse & Trails": return "المؤشر ومسارات الحركة"
            case "Entities & Pets": return "الكائنات والحيوانات الأليفة"
            case "Sounds": return "المؤثرات الصوتية"
            case "Wallpaper": return "خلفية الشاشة"
            case "Motion & FX": return "الحركة والمؤثرات البصرية"
            case "Status Bar": return "شريط القوائم"
            case "VIP Packs": return "باقات VIP الحصرية"
            case "General": return "الإعدادات العامة"
            default: return tab
            }
        default:
            return tab
        }
    }

    public static func searchPlaceholder(lang: String) -> String {
        switch lang {
        case "Español": return "Buscar aplicaciones para abrir u ocultar..."
        case "Français": return "Rechercher des applications à lancer ou masquer..."
        case "Deutsch": return "Apps zum Starten oder Ausblenden suchen..."
        case "日本語": return "起動または非表示にするアプリを検索..."
        case "简体中文": return "搜索要启动或隐藏的应用程序..."
        case "Italiano": return "Cerca app da avviare o nascondere..."
        case "한국어": return "실행하거나 숨길 앱 검색..."
        case "Português": return "Pesquisar aplicativos para abrir ou ocultar..."
        case "العربية": return "البحث عن التطبيقات للفتح أو الإخفاء..."
        default: return "Search apps to launch or hide..."
        }
    }

    public static func defaultGridButton(lang: String) -> String {
        switch lang {
        case "Español": return "Restablecer"
        case "Français": return "Réinitialiser"
        case "Deutsch": return "Zurücksetzen"
        case "日本語": return "初期配置"
        case "简体中文": return "重置网格"
        case "Italiano": return "Reimposta"
        case "한국어": return "격자 초기화"
        case "Português": return "Redefinir"
        case "العربية": return "إعادة تعيين"
        default: return "Default Grid"
        }
    }

    public static func refreshApps(lang: String) -> String {
        switch lang {
        case "Español": return "Recargar Apps"
        case "Français": return "Actualiser les apps"
        case "Deutsch": return "Apps neu laden"
        case "日本語": return "アプリ一覧を更新"
        case "简体中文": return "重新扫描应用"
        case "Italiano": return "Ricarica app"
        case "한국어": return "앱 목록 새로고침"
        case "Português": return "Recarregar Apps"
        case "العربية": return "إعادة تحميل التطبيقات"
        default: return "Refresh Apps"
        }
    }

    public static func quitGenie(lang: String) -> String {
        switch lang {
        case "Español": return "Salir de Genie"
        case "Français": return "Quitter Genie"
        case "Deutsch": return "Genie beenden"
        case "日本語": return "Genie を終了"
        case "简体中文": return "退出 Genie"
        case "Italiano": return "Esci da Genie"
        case "한국어": return "Genie 종료"
        case "Português": return "Encerrar o Genie"
        case "العربية": return "إنهاء Genie"
        default: return "Quit Genie"
        }
    }

    public static func launchAtLogin(lang: String) -> String {
        switch lang {
        case "Español": return "Abrir al iniciar sesión"
        case "Français": return "Ouvrir avec la session"
        case "Deutsch": return "Bei der Anmeldung öffnen"
        case "日本語": return "ログイン時に開く"
        case "简体中文": return "登录时自动打开"
        case "Italiano": return "Apri al login"
        case "한국어": return "로그인 시 자동 열기"
        case "Português": return "Abrir no Início da Sessão"
        case "العربية": return "الفتح عند تسجيل الدخول"
        default: return "Launch at Login"
        }
    }

    // MARK: - Light / Dark Labels
    public static func lightMode(lang: String) -> String {
        switch lang {
        case "Español": return "Claro"
        case "Français": return "Clair"
        case "Deutsch": return "Hell"
        case "日本語": return "ライト"
        case "简体中文": return "浅色"
        case "Italiano": return "Chiaro"
        case "한국어": return "라이트"
        case "Português": return "Claro"
        case "العربية": return "فاتح"
        default: return "Light"
        }
    }

    public static func darkMode(lang: String) -> String {
        switch lang {
        case "Español": return "Oscuro"
        case "Français": return "Sombre"
        case "Deutsch": return "Dunkel"
        case "日本語": return "ダーク"
        case "简体中文": return "深色"
        case "Italiano": return "Scuro"
        case "한국어": return "다크"
        case "Português": return "Escuro"
        case "العربية": return "داكن"
        default: return "Dark"
        }
    }

    // MARK: - Master Toggle ON / OFF
    public static func onLabel(lang: String) -> String {
        switch lang {
        case "Español": return "ACT"
        case "Français": return "OUI"
        case "Deutsch": return "EIN"
        case "日本語": return "オン"
        case "简体中文": return "开启"
        case "Italiano": return "ON"
        case "한국어": return "켜짐"
        case "Português": return "LIG"
        case "العربية": return "مفعّل"
        default: return "ON"
        }
    }

    public static func offLabel(lang: String) -> String {
        switch lang {
        case "Español": return "DES"
        case "Français": return "NON"
        case "Deutsch": return "AUS"
        case "日本語": return "オフ"
        case "简体中文": return "关闭"
        case "Italiano": return "OFF"
        case "한국어": return "꺼짐"
        case "Português": return "DES"
        case "العربية": return "معطّل"
        default: return "OFF"
        }
    }

    // MARK: - Desktop Context Menu Actions
    public static func openApp(name: String, lang: String) -> String {
        switch lang {
        case "Español": return "Abrir \(name)"
        case "Français": return "Ouvrir \(name)"
        case "Deutsch": return "\(name) öffnen"
        case "日本語": return "\(name) を開く"
        case "简体中文": return "打开 \(name)"
        case "Italiano": return "Apri \(name)"
        case "한국어": return "\(name) 열기"
        case "Português": return "Abrir \(name)"
        case "العربية": return "فتح \(name)"
        default: return "Open \(name)"
        }
    }

    public static func showInFinder(lang: String) -> String {
        switch lang {
        case "Español": return "Mostrar en el Finder"
        case "Français": return "Afficher dans le Finder"
        case "Deutsch": return "Im Finder anzeigen"
        case "日本語": return "Finder で表示"
        case "简体中文": return "在访达中显示"
        case "Italiano": return "Mostra nel Finder"
        case "한국어": return "Finder에서 보기"
        case "Português": return "Mostrar no Finder"
        case "العربية": return "إظهار في Finder"
        default: return "Show in Finder"
        }
    }

    public static func hideFromDesktop(lang: String) -> String {
        switch lang {
        case "Español": return "Ocultar del escritorio"
        case "Français": return "Masquer du bureau"
        case "Deutsch": return "Vom Schreibtisch ausblenden"
        case "日本語": return "デスクトップから隠す"
        case "简体中文": return "从桌面隐藏"
        case "Italiano": return "Nascondi dalla scrivania"
        case "한국어": return "데스크탑에서 숨기기"
        case "Português": return "Ocultar da Mesa"
        case "العربية": return "إخفاء من سطح المكتب"
        default: return "Hide from Desktop"
        }
    }

    public static func editAppsAndLayout(lang: String) -> String {
        switch lang {
        case "Español": return "Editar aplicaciones y diseño"
        case "Français": return "Modifier les apps et la disposition"
        case "Deutsch": return "Apps & Layout anpassen"
        case "日本語": return "アプリと配置を編集"
        case "简体中文": return "编辑应用与布局"
        case "Italiano": return "Modifica app e layout"
        case "한국어": return "앱 및 레이아웃 편집"
        case "Português": return "Editar Aplicativos e Layout"
        case "العربية": return "تعديل التطبيقات والتصميم"
        default: return "Edit Apps & Layout"
        }
    }

    public static func hideFromGenie(lang: String) -> String {
        switch lang {
        case "Español": return "Ocultar de Genie"
        case "Français": return "Masquer de Genie"
        case "Deutsch": return "In Genie ausblenden"
        case "日本語": return "Genie から隠す"
        case "简体中文": return "在 Genie 中隐藏"
        case "Italiano": return "Nascondi da Genie"
        case "한국어": return "Genie에서 숨기기"
        case "Português": return "Ocultar do Genie"
        case "العربية": return "إخفاء من Genie"
        default: return "Hide from Genie"
        }
    }

    public static func unhideApp(name: String, lang: String) -> String {
        switch lang {
        case "Español": return "Mostrar \(name)"
        case "Français": return "Afficher \(name)"
        case "Deutsch": return "\(name) einblenden"
        case "日本語": return "\(name) を再表示"
        case "简体中文": return "取消隐藏 \(name)"
        case "Italiano": return "Mostra \(name)"
        case "한국어": return "\(name) 다시 표시"
        case "Português": return "Reexibir \(name)"
        case "العربية": return "إلغاء إخفاء \(name)"
        default: return "Unhide \(name)"
        }
    }

    public static func unhideAllApps(lang: String) -> String {
        switch lang {
        case "Español": return "Mostrar todas las apps"
        case "Français": return "Tout réafficher"
        case "Deutsch": return "Alle Apps einblenden"
        case "日本語": return "すべてのアプリを再表示"
        case "简体中文": return "显示所有已隐藏应用"
        case "Italiano": return "Mostra tutte le app"
        case "한국어": return "모든 앱 다시 표시"
        case "Português": return "Reexibir Todos os Apps"
        case "العربية": return "إلغاء إخفاء جميع التطبيقات"
        default: return "Unhide All Apps"
        }
    }

    public static func manage(lang: String) -> String {
        switch lang {
        case "Español": return "Gestionar"
        case "Français": return "Gérer"
        case "Deutsch": return "Verwalten"
        case "日本語": return "管理"
        case "简体中文": return "管理"
        case "Italiano": return "Gestisci"
        case "한국어": return "관리"
        case "Português": return "Gerenciar"
        case "العربية": return "إدارة"
        default: return "Manage"
        }
    }

    // MARK: - Extended Living Theme Names & Descriptions
    public static func translateText(_ text: String, lang: String) -> String {
        guard lang != "English (US)" else { return text }
        switch lang {
        case "Español":
            switch text {            case "Apps & Desktop": return "Aplicaciones y Escritorio"
            case "Appearance": return "Apariencia"
            case "Interaction": return "Interacción"
            case "System": return "Sistema"
            case "ARRANGEMENT SHAPES": return "FORMAS DE DISPOSICIÓN"
            case "Active Formation": return "Formación activa"
            case "Apps in Formation": return "Apps en formación"
            case "Custom Formation 🛠️": return "Formación personalizada 🛠️"
            case "Custom Formation": return "Formación personalizada"
            case "Search formations...": return "Buscar formaciones..."
            case "Search themes...": return "Buscar temas..."
            case "App Themes": return "Temas de apps"
            case "Icon Snuggies": return "Fundas de iconos"
            case "Columns": return "Columnas"
            case "Basic Shapes 📐": return "Formas básicas 📐"
            case "Infinite Trains & Rails 🚂": return "Trenes y rieles infinitos 🚂"
            case "Kinetic & Orbiting 🔄": return "Cinético y orbital 🔄"
            case "Rectangles & Docks 🔲": return "Rectángulos y docks 🔲"
            case "Geometric & Cosmic 🌌": return "Geométrico y cósmico 🌌"
            case "All": return "Todos"
            case "Orbit & Movement Speed": return "Velocidad de movimiento"
            case "Rotation Direction": return "Dirección de rotación"
            case "Pulse & Elastic Intensity": return "Intensidad de pulso elástico"
            case "Clockwise ↻": return "Horario ↻"
            case "Counter ↺": return "Antihorario ↺"
            case "AUDIO THEME PROFILES": return "PERFILES DE AUDIO"
            case "LIVING PETS & AMBIENT CREATURES": return "MASCOTAS Y CRIATURAS"
            case "MOUSE CURSOR FILTERS & TRAILS": return "FILTROS Y ESTELAS DEL CURSOR"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "DINÁMICA DE FONDO"
            case "Launch at Login": return "Iniciar al arrancar"
            case "Refresh Apps": return "Actualizar aplicaciones"
            case "Quit Genie": return "Salir de Genie"
            case "Reset window back to menu bar": return "Restablecer ventana a barra de menús"
            case "Upload / Select Custom Desktop Wallpaper": return "Subir fondo de escritorio personalizado"
            case "Follow & Play with Cursor": return "Seguir y jugar con el cursor"
            case "Sound Effects & Audio Clicks": return "Efectos de sonido y clics"
            case "Master Audio Volume": return "Volumen de audio maestro"
            case "Trackpad Haptic Pulses": return "Pulsos hápticos del trackpad"
            case "Brand Glyph Icon": return "Icono de marca"
            case "Status Logo": return "Logotipo de estado"

            case "Default": return "Predeterminado"
            case "Classic macOS App Icons": return "Iconos clásicos de macOS"
            case "Translucent": return "Translúcido"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "Vidrio esmerilado aero ultrafino 🪟"
            case "Wallpaper Camouflage": return "Camuflaje de fondo"
            case "Stealth Wallpaper Chameleon 🦎": return "Camaleón invisible en el fondo 🦎"
            case "Dark": return "Oscuro"
            case "Deep Onyx Night Shadows": return "Sombras de noche ónix profundo"
            case "Clear": return "Transparente"
            case "Translucent Frosted Monochrome": return "Monocromo esmerilado translúcido"
            case "Tinted": return "Tintado"
            case "Custom Accent Inset Tint": return "Tinte de acento personalizado"
            case "Vintage Aqua": return "Aqua clásico"
            case "Glossy macOS X Tiger Aqua 💧": return "Aqua brillante de macOS X Tiger 💧"
            case "iOS Minimal": return "iOS Minimalista"
            case "Clean High-Vibrancy Flat": return "Plano limpio de alta vibración"
            case "Frost Glass Acrylic": return "Acrílico esmerilado"
            case "Frosted Acrylic Aero Glass 🪟": return "Vidrio aero acrílico esmerilado 🪟"
            case "Monochrome Studio": return "Estudio monocromo"
            case "Swiss Architectural Minimalist ⚪️": return "Minimalismo arquitectónico suizo ⚪️"
            case "Golden Kintsugi": return "Kintsugi dorado"
            case "Porcelain Repaired with 24K Gold 🏺": return "Porcelana reparada con oro de 24K 🏺"
            case "Desktop Grid": return "Cuadrícula de escritorio"
            case "Always-On Desktop Matrix": return "Matriz de escritorio permanente"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Retardo en Dock (Anti-activación accidental)"
            default: return text
            }
        case "Français":
            switch text {            case "Apps & Desktop": return "Applications & Bureau"
            case "Appearance": return "Apparence"
            case "Interaction": return "Interaction"
            case "System": return "Système"
            case "ARRANGEMENT SHAPES": return "FORMES D'AGENCEMENT"
            case "Active Formation": return "Formation active"
            case "Apps in Formation": return "Apps en formation"
            case "Custom Formation 🛠️": return "Formation personnalisée 🛠️"
            case "Custom Formation": return "Formation personnalisée"
            case "Search formations...": return "Rechercher des formations..."
            case "Search themes...": return "Rechercher des thèmes..."
            case "App Themes": return "Thèmes d'apps"
            case "Icon Snuggies": return "Enveloppes d'icônes"
            case "Columns": return "Colonnes"
            case "Basic Shapes 📐": return "Formes basiques 📐"
            case "Infinite Trains & Rails 🚂": return "Trains & Rails infinis 🚂"
            case "Kinetic & Orbiting 🔄": return "Cinétique & Orbital 🔄"
            case "Rectangles & Docks 🔲": return "Rectangles & Docks 🔲"
            case "Geometric & Cosmic 🌌": return "Géométrique & Cosmique 🌌"
            case "All": return "Tout"
            case "Orbit & Movement Speed": return "Vitesse d'orbite et mouvement"
            case "Rotation Direction": return "Sens de rotation"
            case "Pulse & Elastic Intensity": return "Intensité de pulsation élastique"
            case "Clockwise ↻": return "Sens horaire ↻"
            case "Counter ↺": return "Antihoraire ↺"
            case "AUDIO THEME PROFILES": return "PROFILS AUDIO"
            case "LIVING PETS & AMBIENT CREATURES": return "COMPAGNONS & CRÉATURES"
            case "MOUSE CURSOR FILTERS & TRAILS": return "FILTRES & TRAÎNÉES DE SOURIS"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "DYNAMIQUE DU FOND D'ÉCRAN"
            case "Launch at Login": return "Lancer au démarrage"
            case "Refresh Apps": return "Actualiser les applications"
            case "Quit Genie": return "Quitter Genie"
            case "Reset window back to menu bar": return "Réinitialiser la fenêtre dans la barre des menus"
            case "Upload / Select Custom Desktop Wallpaper": return "Importer un fond d'écran personnalisé"
            case "Follow & Play with Cursor": return "Suivre et jouer avec le curseur"
            case "Sound Effects & Audio Clicks": return "Effets sonores & clics"
            case "Master Audio Volume": return "Volume audio principal"
            case "Trackpad Haptic Pulses": return "Vibrations haptiques du trackpad"
            case "Brand Glyph Icon": return "Glyphe de marque"
            case "Status Logo": return "Logo d'état"

            case "Default": return "Par défaut"
            case "Classic macOS App Icons": return "Icônes d'applications macOS classiques"
            case "Translucent": return "Translucide"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "Verre dépoli aéro ultra-fin 🪟"
            case "Wallpaper Camouflage": return "Camouflage fond d'écran"
            case "Stealth Wallpaper Chameleon 🦎": return "Caméléon furtif de fond d'écran 🦎"
            case "Dark": return "Sombre"
            case "Deep Onyx Night Shadows": return "Ombres de nuit onyx profond"
            case "Clear": return "Transparent"
            case "Translucent Frosted Monochrome": return "Monochrome dépoli translucide"
            case "Tinted": return "Teinté"
            case "Custom Accent Inset Tint": return "Teinte d'accent personnalisée"
            case "Vintage Aqua": return "Aqua vintage"
            case "Glossy macOS X Tiger Aqua 💧": return "Aqua brillant macOS X Tiger 💧"
            case "iOS Minimal": return "iOS Minimaliste"
            case "Clean High-Vibrancy Flat": return "Design plat vibrant et épuré"
            case "Frost Glass Acrylic": return "Acrylique dépoli"
            case "Frosted Acrylic Aero Glass 🪟": return "Verre aéro acrylique dépoli 🪟"
            case "Monochrome Studio": return "Studio Monochrome"
            case "Swiss Architectural Minimalist ⚪️": return "Minimalisme architectural suisse ⚪️"
            case "Golden Kintsugi": return "Kintsugi doré"
            case "Porcelain Repaired with 24K Gold 🏺": return "Porcelaine réparée à l'or 24 carats 🏺"
            case "Desktop Grid": return "Grille du bureau"
            case "Always-On Desktop Matrix": return "Matrice de bureau permanente"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Délai sur le Dock (Anti-survol accidentel)"
            default: return text
            }
        case "Deutsch":
            switch text {            case "Apps & Desktop": return "Apps & Schreibtisch"
            case "Appearance": return "Erscheinungsbild"
            case "Interaction": return "Interaktion"
            case "System": return "System"
            case "ARRANGEMENT SHAPES": return "ANORDNUNGSFORMEN"
            case "Active Formation": return "Aktive Formation"
            case "Apps in Formation": return "Apps in Formation"
            case "Custom Formation 🛠️": return "Benutzerdefinierte Formation 🛠️"
            case "Custom Formation": return "Benutzerdefinierte Formation"
            case "Search formations...": return "Formationen suchen..."
            case "Search themes...": return "Designs suchen..."
            case "App Themes": return "App-Designs"
            case "Icon Snuggies": return "Symbol-Hüllen"
            case "Columns": return "Spalten"
            case "Basic Shapes 📐": return "Grundformen 📐"
            case "Infinite Trains & Rails 🚂": return "Unendliche Züge & Schienen 🚂"
            case "Kinetic & Orbiting 🔄": return "Kinetisch & Umlaufend 🔄"
            case "Rectangles & Docks 🔲": return "Rechtecke & Docks 🔲"
            case "Geometric & Cosmic 🌌": return "Geometrisch & Kosmisch 🌌"
            case "All": return "Alle"
            case "Orbit & Movement Speed": return "Umlauf- & Bewegungsgeschwindigkeit"
            case "Rotation Direction": return "Drehrichtung"
            case "Pulse & Elastic Intensity": return "Impuls- & Elastizitätsintensität"
            case "Clockwise ↻": return "Im Uhrzeigersinn ↻"
            case "Counter ↺": return "Gegen Uhrzeigersinn ↺"
            case "AUDIO THEME PROFILES": return "AUDIO-PROFILE"
            case "LIVING PETS & AMBIENT CREATURES": return "BEGLEITER & WESEN"
            case "MOUSE CURSOR FILTERS & TRAILS": return "MAUSZEIGER-FILTER & SPUREN"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "HINTERGRUNDBILD-DYNAMIK"
            case "Launch at Login": return "Beim Systemstart öffnen"
            case "Refresh Apps": return "Apps aktualisieren"
            case "Quit Genie": return "Genie beenden"
            case "Reset window back to menu bar": return "Fenster an Menüleiste zurücksetzen"
            case "Upload / Select Custom Desktop Wallpaper": return "Eigenes Hintergrundbild auswählen"
            case "Follow & Play with Cursor": return "Mauszeiger folgen und spielen"
            case "Sound Effects & Audio Clicks": return "Soundeffekte & Audioklicks"
            case "Master Audio Volume": return "Gesamtlautstärke"
            case "Trackpad Haptic Pulses": return "Haptisches Trackpad-Feedback"
            case "Brand Glyph Icon": return "Marken-Symbol"
            case "Status Logo": return "Status-Logo"

            case "Default": return "Standard"
            case "Classic macOS App Icons": return "Klassische macOS App-Symbole"
            case "Translucent": return "Transluzent"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "Hauchdünnes Milchglas & Aero-Glow 🪟"
            case "Wallpaper Camouflage": return "Hintergrund-Tarnung"
            case "Stealth Wallpaper Chameleon 🦎": return "Unsichtbares Hintergrund-Chamäleon 🦎"
            case "Dark": return "Dunkel"
            case "Deep Onyx Night Shadows": return "Tiefe Onyx-Nachtschatten"
            case "Clear": return "Klar"
            case "Translucent Frosted Monochrome": return "Transluzentes mattes Monochrom"
            case "Tinted": return "Getönt"
            case "Custom Accent Inset Tint": return "Benutzerdefinierte Akzenttönung"
            case "Vintage Aqua": return "Klassisches Aqua"
            case "Glossy macOS X Tiger Aqua 💧": return "Glänzendes macOS X Tiger Aqua 💧"
            case "iOS Minimal": return "iOS Minimal"
            case "Clean High-Vibrancy Flat": return "Klares, farbintensives Flachdesign"
            case "Frost Glass Acrylic": return "Acryl-Milchglas"
            case "Frosted Acrylic Aero Glass 🪟": return "Mattes Acryl-Aero-Glas 🪟"
            case "Monochrome Studio": return "Monochrom-Studio"
            case "Swiss Architectural Minimalist ⚪️": return "Schweizer Architektur-Minimalismus ⚪️"
            case "Golden Kintsugi": return "Goldenes Kintsugi"
            case "Porcelain Repaired with 24K Gold 🏺": return "Mit 24K Gold repariertes Porzellan 🏺"
            case "Desktop Grid": return "Schreibtisch-Gitter"
            case "Always-On Desktop Matrix": return "Permanente Schreibtisch-Matrix"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Dock-Verzögerung (Schutz vor versehentlichem Berühren)"
            default: return text
            }
        case "日本語":
            switch text {            case "Apps & Desktop": return "アプリ & デスクトップ"
            case "Appearance": return "外観"
            case "Interaction": return "操作・演出"
            case "System": return "システム"
            case "ARRANGEMENT SHAPES": return "配置パターン"
            case "Active Formation": return "選択中のフォーメーション"
            case "Apps in Formation": return "配置アプリ数"
            case "Custom Formation 🛠️": return "カスタムフォーメーション 🛠️"
            case "Custom Formation": return "カスタムフォーメーション"
            case "Search formations...": return "フォーメーションを検索..."
            case "Search themes...": return "テーマを検索..."
            case "App Themes": return "アプリテーマ"
            case "Icon Snuggies": return "アイコンスナギー"
            case "Columns": return "列数"
            case "Basic Shapes 📐": return "基本図形 📐"
            case "Infinite Trains & Rails 🚂": return "トレイン & レール 🚂"
            case "Kinetic & Orbiting 🔄": return "回転 & オービット 🔄"
            case "Rectangles & Docks 🔲": return "ドック & グリッド 🔲"
            case "Geometric & Cosmic 🌌": return "コズミック & ジオメトリック 🌌"
            case "All": return "すべて"
            case "Orbit & Movement Speed": return "周回・移動速度"
            case "Rotation Direction": return "回転方向"
            case "Pulse & Elastic Intensity": return "パルス強度"
            case "Clockwise ↻": return "時計回り ↻"
            case "Counter ↺": return "反時計回り ↺"
            case "AUDIO THEME PROFILES": return "オーディオテーマ"
            case "LIVING PETS & AMBIENT CREATURES": return "ペット & コンパニオン"
            case "MOUSE CURSOR FILTERS & TRAILS": return "カーソルトレイル"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "壁紙エフェクト"
            case "Launch at Login": return "ログイン時に起動"
            case "Refresh Apps": return "アプリを再読込"
            case "Quit Genie": return "Genie を終了"
            case "Reset window back to menu bar": return "ウィンドウ位置を初期化"
            case "Upload / Select Custom Desktop Wallpaper": return "カスタム壁紙を選択"
            case "Follow & Play with Cursor": return "カーソルに追従して遊ぶ"
            case "Sound Effects & Audio Clicks": return "効果音とクリック音"
            case "Master Audio Volume": return "マスター音量"
            case "Trackpad Haptic Pulses": return "トラックパッド触覚フィードバック"
            case "Brand Glyph Icon": return "ブランドアイコン"
            case "Status Logo": return "ステータスロゴ"

            case "Default": return "デフォルト"
            case "Classic macOS App Icons": return "クラシック macOS アプリアイコン"
            case "Translucent": return "半透明"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "極薄すりガラス＆エアログロー 🪟"
            case "Wallpaper Camouflage": return "壁紙カモフラージュ"
            case "Stealth Wallpaper Chameleon 🦎": return "ステルス壁紙カメレオン 🦎"
            case "Dark": return "ダーク"
            case "Deep Onyx Night Shadows": return "ディープオニキスナイトシャドウ"
            case "Clear": return "クリア"
            case "Translucent Frosted Monochrome": return "半透明すりガラスモノクローム"
            case "Tinted": return "着色"
            case "Custom Accent Inset Tint": return "カスタムアクセントカラーティント"
            case "Vintage Aqua": return "ヴィンテージアクア"
            case "Glossy macOS X Tiger Aqua 💧": return "光沢ある macOS X Tiger Aqua 💧"
            case "iOS Minimal": return "iOS ミニマル"
            case "Clean High-Vibrancy Flat": return "クリーンで鮮やかなフラットデザイン"
            case "Frost Glass Acrylic": return "フロストガラスアクリル"
            case "Frosted Acrylic Aero Glass 🪟": return "すりガラス風アクリルエアロガラス 🪟"
            case "Monochrome Studio": return "モノクロームスタジオ"
            case "Swiss Architectural Minimalist ⚪️": return "スイス建築ミニマリズム ⚪️"
            case "Golden Kintsugi": return "金継ぎ"
            case "Porcelain Repaired with 24K Gold 🏺": return "24金で修復された陶器 🏺"
            case "Desktop Grid": return "デスクトップグリッド"
            case "Always-On Desktop Matrix": return "常時表示デスクトップマトリックス"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Dock停止時間 (誤操作防止ディレイ)"
            default: return text
            }
        case "简体中文":
            switch text {            case "Apps & Desktop": return "应用与桌面"
            case "Appearance": return "外观风格"
            case "Interaction": return "交互与特效"
            case "System": return "系统设置"
            case "ARRANGEMENT SHAPES": return "排列造型"
            case "Active Formation": return "当前排列形态"
            case "Apps in Formation": return "阵列应用数量"
            case "Custom Formation 🛠️": return "自定义阵列 🛠️"
            case "Custom Formation": return "自定义阵列"
            case "Search formations...": return "搜索阵列形态..."
            case "Search themes...": return "搜索主题..."
            case "App Themes": return "应用主题"
            case "Icon Snuggies": return "图标保护套"
            case "Columns": return "列数"
            case "Basic Shapes 📐": return "基础几何 📐"
            case "Infinite Trains & Rails 🚂": return "无限轨道 🚂"
            case "Kinetic & Orbiting 🔄": return "动态环绕 🔄"
            case "Rectangles & Docks 🔲": return "桌面坞格 🔲"
            case "Geometric & Cosmic 🌌": return "星系宇宙 🌌"
            case "All": return "全部"
            case "Orbit & Movement Speed": return "公转与移动速度"
            case "Rotation Direction": return "旋转方向"
            case "Pulse & Elastic Intensity": return "脉冲与弹性强度"
            case "Clockwise ↻": return "顺时针 ↻"
            case "Counter ↺": return "逆时针 ↺"
            case "AUDIO THEME PROFILES": return "音效主题"
            case "LIVING PETS & AMBIENT CREATURES": return "桌面宠物与陪伴生物"
            case "MOUSE CURSOR FILTERS & TRAILS": return "光标轨迹滤镜"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "动态壁纸特效"
            case "Launch at Login": return "开机自启动"
            case "Refresh Apps": return "刷新应用列表"
            case "Quit Genie": return "退出 Genie"
            case "Reset window back to menu bar": return "重置窗口停靠位置"
            case "Upload / Select Custom Desktop Wallpaper": return "上传自定义壁纸"
            case "Follow & Play with Cursor": return "跟随光标互动"
            case "Sound Effects & Audio Clicks": return "交互音效与点击反馈"
            case "Master Audio Volume": return "主音量"
            case "Trackpad Haptic Pulses": return "触控板触觉反馈"
            case "Brand Glyph Icon": return "品牌图标"
            case "Status Logo": return "状态徽标"

            case "Default": return "默认"
            case "Classic macOS App Icons": return "经典 macOS 应用程序图标"
            case "Translucent": return "半透明磨砂"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "超薄磨砂玻璃与航空光晕 🪟"
            case "Wallpaper Camouflage": return "壁纸伪装"
            case "Stealth Wallpaper Chameleon 🦎": return "隐形壁纸变色龙 🦎"
            case "Dark": return "暗黑深色"
            case "Deep Onyx Night Shadows": return "深黑玛瑙夜间暗影"
            case "Clear": return "极简透明"
            case "Translucent Frosted Monochrome": return "半透明磨砂单色"
            case "Tinted": return "个性色调"
            case "Custom Accent Inset Tint": return "自定义内嵌强调色调"
            case "Vintage Aqua": return "复古水滴 Aqua"
            case "Glossy macOS X Tiger Aqua 💧": return "经典高光 macOS X Tiger Aqua 💧"
            case "iOS Minimal": return "iOS 极简"
            case "Clean High-Vibrancy Flat": return "清爽高饱和度扁平设计"
            case "Frost Glass Acrylic": return "磨砂亚克力玻璃"
            case "Frosted Acrylic Aero Glass 🪟": return "磨砂亚克力航空玻璃 🪟"
            case "Monochrome Studio": return "黑白影棚"
            case "Swiss Architectural Minimalist ⚪️": return "瑞士建筑极简风格 ⚪️"
            case "Golden Kintsugi": return "黄金金缮"
            case "Porcelain Repaired with 24K Gold 🏺": return "24K 纯金修缮瓷器 🏺"
            case "Desktop Grid": return "桌面网格"
            case "Always-On Desktop Matrix": return "常驻桌面矩阵"
            case "Dock Rest Period (Anti-Accidental Hover)": return "程序坞停留时间 (防误触延迟)"
            default: return text
            }
        case "Italiano":
            switch text {            case "Apps & Desktop": return "Applicazioni & Scrivania"
            case "Appearance": return "Aspetto"
            case "Interaction": return "Interazione"
            case "System": return "Sistema"
            case "ARRANGEMENT SHAPES": return "FORME DI DISPOSIZIONE"
            case "Active Formation": return "Formazione attiva"
            case "Apps in Formation": return "App in formazione"
            case "Custom Formation 🛠️": return "Formazione personalizzata 🛠️"
            case "Custom Formation": return "Formazione personalizzata"
            case "Search formations...": return "Cerca formazioni..."
            case "Search themes...": return "Cerca temi..."
            case "App Themes": return "Temi delle app"
            case "Icon Snuggies": return "Involucri per icone"
            case "Columns": return "Colonne"
            case "Basic Shapes 📐": return "Forme base 📐"
            case "Infinite Trains & Rails 🚂": return "Treni e binari infiniti 🚂"
            case "Kinetic & Orbiting 🔄": return "Cinetico e orbitale 🔄"
            case "Rectangles & Docks 🔲": return "Rettangoli e dock 🔲"
            case "Geometric & Cosmic 🌌": return "Geometrico e cosmico 🌌"
            case "All": return "Tutto"
            case "Orbit & Movement Speed": return "Velocità orbita e movimento"
            case "Rotation Direction": return "Direzione di rotazione"
            case "Pulse & Elastic Intensity": return "Intensità impulsi elastici"
            case "Clockwise ↻": return "Orario ↻"
            case "Counter ↺": return "Antiorario ↺"
            case "AUDIO THEME PROFILES": return "PROFILI AUDIO"
            case "LIVING PETS & AMBIENT CREATURES": return "ANIMALI & CREATURE"
            case "MOUSE CURSOR FILTERS & TRAILS": return "FILTRI E SCIE DEL CURSORE"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "DINAMICA DELLO SFONDO"
            case "Launch at Login": return "Avvia al login"
            case "Refresh Apps": return "Aggiorna applicazioni"
            case "Quit Genie": return "Esci da Genie"
            case "Reset window back to menu bar": return "Reimposta finestra nella barra menu"
            case "Upload / Select Custom Desktop Wallpaper": return "Carica sfondo personalizzato"
            case "Follow & Play with Cursor": return "Segui e gioca con il cursore"
            case "Sound Effects & Audio Clicks": return "Effetti sonori e clic"
            case "Master Audio Volume": return "Volume principale"
            case "Trackpad Haptic Pulses": return "Feedback aptico del trackpad"
            case "Brand Glyph Icon": return "Icona del brand"
            case "Status Logo": return "Logo di stato"

            case "Default": return "Predefinito"
            case "Classic macOS App Icons": return "Icone classiche delle app macOS"
            case "Translucent": return "Traslucido"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "Vetro satinato ultra-sottile e bagliore aero 🪟"
            case "Wallpaper Camouflage": return "Camuffamento sfondo"
            case "Stealth Wallpaper Chameleon 🦎": return "Camaleonte mimetico per sfondo 🦎"
            case "Dark": return "Scuro"
            case "Deep Onyx Night Shadows": return "Ombre notturne onice profondo"
            case "Clear": return "Trasparente"
            case "Translucent Frosted Monochrome": return "Monocromo satinato traslucido"
            case "Tinted": return "Colorato"
            case "Custom Accent Inset Tint": return "Tinta personalizzata"
            case "Vintage Aqua": return "Aqua classico"
            case "Glossy macOS X Tiger Aqua 💧": return "Aqua lucido di macOS X Tiger 💧"
            case "iOS Minimal": return "iOS Minimalista"
            case "Clean High-Vibrancy Flat": return "Design piatto pulito e vivace"
            case "Frost Glass Acrylic": return "Acrilico satinato"
            case "Frosted Acrylic Aero Glass 🪟": return "Vetro satinato aero acrilico 🪟"
            case "Monochrome Studio": return "Studio monocromatico"
            case "Swiss Architectural Minimalist ⚪️": return "Minimalismo architettonico svizzero ⚪️"
            case "Golden Kintsugi": return "Kintsugi d'oro"
            case "Porcelain Repaired with 24K Gold 🏺": return "Porcellana riparata con oro 24 carati 🏺"
            case "Desktop Grid": return "Griglia scrivania"
            case "Always-On Desktop Matrix": return "Matrice scrivania sempre attiva"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Ritardo su Dock (Anti-passaggio accidentale)"
            default: return text
            }
        case "한국어":
            switch text {            case "Apps & Desktop": return "앱 & 데스크탑"
            case "Appearance": return "화면 스타일"
            case "Interaction": return "인터랙션 및 효과"
            case "System": return "시스템 설정"
            case "ARRANGEMENT SHAPES": return "배치 형태"
            case "Active Formation": return "현재 활성 대형"
            case "Apps in Formation": return "대형 내 앱 수"
            case "Custom Formation 🛠️": return "사용자 지정 대형 🛠️"
            case "Custom Formation": return "사용자 지정 대형"
            case "Search formations...": return "대형 검색..."
            case "Search themes...": return "테마 검색..."
            case "App Themes": return "앱 테마"
            case "Icon Snuggies": return "아이콘 스너기"
            case "Columns": return "열 수"
            case "Basic Shapes 📐": return "기본 도형 📐"
            case "Infinite Trains & Rails 🚂": return "무한 열차 & 레일 🚂"
            case "Kinetic & Orbiting 🔄": return "키네틱 & 궤도 🔄"
            case "Rectangles & Docks 🔲": return "직사각형 & 독 🔲"
            case "Geometric & Cosmic 🌌": return "기하학 & 코스믹 🌌"
            case "All": return "전체"
            case "Orbit & Movement Speed": return "공전 및 이동 속도"
            case "Rotation Direction": return "회전 방향"
            case "Pulse & Elastic Intensity": return "펄스 및 탄성 강도"
            case "Clockwise ↻": return "시계 방향 ↻"
            case "Counter ↺": return "반시계 방향 ↺"
            case "AUDIO THEME PROFILES": return "오디오 테마 프로필"
            case "LIVING PETS & AMBIENT CREATURES": return "생생한 펫 & 컴패니언"
            case "MOUSE CURSOR FILTERS & TRAILS": return "마우스 커서 트레일"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "배경화면 다이내믹"
            case "Launch at Login": return "로그인 시 자동 실행"
            case "Refresh Apps": return "앱 새로고침"
            case "Quit Genie": return "Genie 종료"
            case "Reset window back to menu bar": return "메뉴 바로 창 위치 재설정"
            case "Upload / Select Custom Desktop Wallpaper": return "사용자 배경화면 업로드"
            case "Follow & Play with Cursor": return "커서 따라다니기 및 놀기"
            case "Sound Effects & Audio Clicks": return "사운드 효과 및 클릭음"
            case "Master Audio Volume": return "마스터 음량"
            case "Trackpad Haptic Pulses": return "트랙패드 햅틱 피드백"
            case "Brand Glyph Icon": return "브랜드 아이콘"
            case "Status Logo": return "상태 로고"

            case "Default": return "기본값"
            case "Classic macOS App Icons": return "클래식 macOS 앱 아이콘"
            case "Translucent": return "반투명"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "초박형 반투명 유리 및 에어로 글로우 🪟"
            case "Wallpaper Camouflage": return "배경화면 위장"
            case "Stealth Wallpaper Chameleon 🦎": return "은신 배경화면 카멜레온 🦎"
            case "Dark": return "다크 모드"
            case "Deep Onyx Night Shadows": return "깊은 오닉스 야간 그림자"
            case "Clear": return "투명"
            case "Translucent Frosted Monochrome": return "반투명 모노크롬"
            case "Tinted": return "틴트 색상"
            case "Custom Accent Inset Tint": return "사용자 지정 강조 틴트"
            case "Vintage Aqua": return "빈티지 아쿠아"
            case "Glossy macOS X Tiger Aqua 💧": return "광택있는 macOS X Tiger Aqua 💧"
            case "iOS Minimal": return "iOS 미니멀"
            case "Clean High-Vibrancy Flat": return "깔끔하고 선명한 플랫 디자인"
            case "Frost Glass Acrylic": return "프로스트 유리 아크릴"
            case "Frosted Acrylic Aero Glass 🪟": return "반투명 아크릴 에어로 유리 🪟"
            case "Monochrome Studio": return "모노크롬 스튜디오"
            case "Swiss Architectural Minimalist ⚪️": return "스위스 건축 미니멀리즘 ⚪️"
            case "Golden Kintsugi": return "골든 킨츠기"
            case "Porcelain Repaired with 24K Gold 🏺": return "24K 금으로 복원된 자기 🏺"
            case "Desktop Grid": return "데스크탑 그리드"
            case "Always-On Desktop Matrix": return "상시 활성 데스크탑 매트릭스"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Dock 체류 시간 (실행 지연 방지)"
            default: return text
            }
        case "Português":
            switch text {            case "Apps & Desktop": return "Aplicativos & Mesa"
            case "Appearance": return "Aparência"
            case "Interaction": return "Interação"
            case "System": return "Sistema"
            case "ARRANGEMENT SHAPES": return "FORMAS DE DISPOSIÇÃO"
            case "Active Formation": return "Formação ativa"
            case "Apps in Formation": return "Apps na formação"
            case "Custom Formation 🛠️": return "Formação personalizada 🛠️"
            case "Custom Formation": return "Formação personalizada"
            case "Search formations...": return "Buscar formações..."
            case "Search themes...": return "Buscar temas..."
            case "App Themes": return "Temas de aplicativos"
            case "Icon Snuggies": return "Envoltórios de ícones"
            case "Columns": return "Colunas"
            case "Basic Shapes 📐": return "Formas básicas 📐"
            case "Infinite Trains & Rails 🚂": return "Trens e trilhos infinitos 🚂"
            case "Kinetic & Orbiting 🔄": return "Cinético e orbital 🔄"
            case "Rectangles & Docks 🔲": return "Retângulos e docks 🔲"
            case "Geometric & Cosmic 🌌": return "Geométrico e cósmico 🌌"
            case "All": return "Todos"
            case "Orbit & Movement Speed": return "Velocidade de órbita e movimento"
            case "Rotation Direction": return "Direção de rotação"
            case "Pulse & Elastic Intensity": return "Intensidade de pulso elástico"
            case "Clockwise ↻": return "Horário ↻"
            case "Counter ↺": return "Anti-horário ↺"
            case "AUDIO THEME PROFILES": return "PERFIS DE ÁUDIO"
            case "LIVING PETS & AMBIENT CREATURES": return "PETS & CRIATURAS"
            case "MOUSE CURSOR FILTERS & TRAILS": return "FILTROS E RASTROS DO CURSOR"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "DINÂMICA DE PAPEL DE PAREDE"
            case "Launch at Login": return "Iniciar no login"
            case "Refresh Apps": return "Atualizar aplicativos"
            case "Quit Genie": return "Encerrar Genie"
            case "Reset window back to menu bar": return "Redefinir janela para barra de menus"
            case "Upload / Select Custom Desktop Wallpaper": return "Enviar papel de parede personalizado"
            case "Follow & Play with Cursor": return "Seguir e brincar com o cursor"
            case "Sound Effects & Audio Clicks": return "Efeitos sonoros e cliques"
            case "Master Audio Volume": return "Volume mestre de áudio"
            case "Trackpad Haptic Pulses": return "Pulsos táteis do trackpad"
            case "Brand Glyph Icon": return "Ícone da marca"
            case "Status Logo": return "Logotipo de status"

            case "Default": return "Padrão"
            case "Classic macOS App Icons": return "Ícones clássicos do macOS"
            case "Translucent": return "Translúcido"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "Vidro fosco ultrafino e brilho aero 🪟"
            case "Wallpaper Camouflage": return "Camuflagem de fundo"
            case "Stealth Wallpaper Chameleon 🦎": return "Camaleão invisível no fundo 🦎"
            case "Dark": return "Escuro"
            case "Deep Onyx Night Shadows": return "Sombras noturnas de ônix profundo"
            case "Clear": return "Transparente"
            case "Translucent Frosted Monochrome": return "Monocromático fosco translúcido"
            case "Tinted": return "Colorido"
            case "Custom Accent Inset Tint": return "Tonalidade personalizada"
            case "Vintage Aqua": return "Aqua clássico"
            case "Glossy macOS X Tiger Aqua 💧": return "Aqua brilhante macOS X Tiger 💧"
            case "iOS Minimal": return "iOS Minimalista"
            case "Clean High-Vibrancy Flat": return "Design plano limpo e vibrante"
            case "Frost Glass Acrylic": return "Acrílico fosco"
            case "Frosted Acrylic Aero Glass 🪟": return "Vidro aero acrílico fosco 🪟"
            case "Monochrome Studio": return "Estúdio monocromático"
            case "Swiss Architectural Minimalist ⚪️": return "Minimalismo arquitetônico suíço ⚪️"
            case "Golden Kintsugi": return "Kintsugi dourado"
            case "Porcelain Repaired with 24K Gold 🏺": return "Porcelana reparada com ouro 24K 🏺"
            case "Desktop Grid": return "Grade da Área de Trabalho"
            case "Always-On Desktop Matrix": return "Matriz de mesa permanente"
            case "Dock Rest Period (Anti-Accidental Hover)": return "Atraso no Dock (Evitar acionamento acidental)"
            default: return text
            }
        case "العربية":
            switch text {            case "Apps & Desktop": return "التطبيقات وسطح المكتب"
            case "Appearance": return "المظهر والسمات"
            case "Interaction": return "التفاعل والمؤثرات"
            case "System": return "إعدادات النظام"
            case "ARRANGEMENT SHAPES": return "أشكال الترتيب والتوزيع"
            case "Active Formation": return "التشكيل النشط"
            case "Apps in Formation": return "التطبيقات في التشكيل"
            case "Custom Formation 🛠️": return "تشكيل مخصص 🛠️"
            case "Custom Formation": return "تشكيل مخصص"
            case "Search formations...": return "البحث في التشكيلات..."
            case "Search themes...": return "البحث في السمات..."
            case "App Themes": return "سمات التطبيقات"
            case "Icon Snuggies": return "أغلفة الأيقونات"
            case "Columns": return "الأعمدة"
            case "Basic Shapes 📐": return "أشكال هندسية بسيطة 📐"
            case "Infinite Trains & Rails 🚂": return "قطارات ومسارات لا نهائية 🚂"
            case "Kinetic & Orbiting 🔄": return "حركي ومداري 🔄"
            case "Rectangles & Docks 🔲": return "مستطيلات وأرصفة 🔲"
            case "Geometric & Cosmic 🌌": return "كوني وهندسي 🌌"
            case "All": return "الكل"
            case "Orbit & Movement Speed": return "سرعة الدوران والحركة"
            case "Rotation Direction": return "اتجاه الدوران"
            case "Pulse & Elastic Intensity": return "شدة النبض والمرونة"
            case "Clockwise ↻": return "مع عقارب الساعة ↻"
            case "Counter ↺": return "عكس عقارب الساعة ↺"
            case "AUDIO THEME PROFILES": return "الملفات الصوتية"
            case "LIVING PETS & AMBIENT CREATURES": return "حيوانات أليفة وكائنات مرافقة"
            case "MOUSE CURSOR FILTERS & TRAILS": return "مرشحات ومسارات المؤشر"
            case "POP-UP APPS GRID WALLPAPER DYNAMICS": return "ديناميكيات الخلفية"
            case "Launch at Login": return "التشغيل عند بدء التشغيل"
            case "Refresh Apps": return "تحديث التطبيقات"
            case "Quit Genie": return "إنهاء Genie"
            case "Reset window back to menu bar": return "إعادة تعيين النافذة إلى شريط القوائم"
            case "Upload / Select Custom Desktop Wallpaper": return "تحميل خلفية مخصصة"
            case "Follow & Play with Cursor": return "تتبع المؤشر واللعب معه"
            case "Sound Effects & Audio Clicks": return "مؤثرات صوتية ونقرات"
            case "Master Audio Volume": return "مستوى الصوت الرئيسي"
            case "Trackpad Haptic Pulses": return "استجابة لمسية للوحة اللمس"
            case "Brand Glyph Icon": return "أيقونة العلامة التجارية"
            case "Status Logo": return "شعار الحالة"

            case "Default": return "الافتراضي"
            case "Classic macOS App Icons": return "أيقونات تطبيقات macOS الكلاسيكية"
            case "Translucent": return "شبه شفاف"
            case "Ultra-Thin Frosted Glass & Aero Glow 🪟": return "زجاج مثلج فائق الرقة مع توهج هوائي 🪟"
            case "Wallpaper Camouflage": return "تمويه الخلفية"
            case "Stealth Wallpaper Chameleon 🦎": return "حرباء خلفية الشاشة المتخفية 🦎"
            case "Dark": return "داكن"
            case "Deep Onyx Night Shadows": return "ظلال الليل العميقة"
            case "Clear": return "شفاف"
            case "Translucent Frosted Monochrome": return "أحادي اللون مثلج شبه شفاف"
            case "Tinted": return "ملوّن"
            case "Custom Accent Inset Tint": return "صبغة مخصصة"
            case "Vintage Aqua": return "أكوا كلاسيكي"
            case "Glossy macOS X Tiger Aqua 💧": return "أكوا لامع من macOS X Tiger 💧"
            case "iOS Minimal": return "iOS بسيط"
            case "Clean High-Vibrancy Flat": return "تصميم مسطح ونقي عالي الحيوية"
            case "Frost Glass Acrylic": return "أكريليك مثلج"
            case "Frosted Acrylic Aero Glass 🪟": return "زجاج هوائي أكريليك مثلج 🪟"
            case "Monochrome Studio": return "استوديو أحادي اللون"
            case "Swiss Architectural Minimalist ⚪️": return "بساطة معمارية سويسرية ⚪️"
            case "Golden Kintsugi": return "كينتسوجي ذهبي"
            case "Porcelain Repaired with 24K Gold 🏺": return "خزف مصلح بذهب عيار 24 🏺"
            case "Desktop Grid": return "شبكة سطح المكتب"
            case "Always-On Desktop Matrix": return "مصفوفة سطح المكتب الدائمة"
            case "Dock Rest Period (Anti-Accidental Hover)": return "مهلة استقرار Dock (لمنع التحفيز العرضي)"
            default: return text
            }
        default:
            return text
        }
    }
}
