// swift-tools-version: 6.0
import PackageDescription

// Genie's iOS client: Chat, Editor, Files, sharing the same tool-calling
// protocol as the Mac app. Local model inference (Ollama) doesn't exist on
// iOS, so this talks to a remote OpenAI-compatible endpoint — typically the
// user's own Mac running Ollama on the same network — via the same
// AgentHTTPModel the Mac app's Agent 3.0 workspace already uses.
//
// This is a plain library so `swift build`/SourceKit can type-check it
// directly. The actual installable app is generated by xcodegen from
// project.yml in this directory (`xcodegen generate`), which compiles these
// same source files straight into a real iOS app target — see project.yml
// for the app-shell details (bundle id, Info.plist, signing) SwiftPM alone
// can't produce for iOS.
let package = Package(
    name: "GenieMobile",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "GenieMobile", targets: ["GenieMobile"])
    ],
    dependencies: [
        .package(path: "../AgentRuntime")
    ],
    targets: [
        .target(
            name: "GenieMobile",
            dependencies: [.product(name: "GenieAgentCore", package: "AgentRuntime")]
        )
    ]
)
